name: 'Continuous Integration'

on: [push]


jobs:
  run-tests:
    name: Run Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install test requirements
        run: pip install -r requirements-test.txt

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run model tests
        run: make model-test

      - name: Run api tests
        run: make api-test